# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 460ada21fec6cd4c974fdbc0b46dbcd6f4fb153f2b0c346a684d4bf8421df689cdf5e30de1fb1c45ceef47dfdd6a3993801a28daa64e227c7450b17bad30daad

test:
  secret_key_base: ca202fbf5ad48d040fcf8a5376e71076de4b7b19730cf80b83cf7ed3f9a7f0252d61b7c30150dc6d74a2acb9972c3dc36ee5ccaf31292a9aee43a7b3e9df2e05

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
